remote_theme: jackw01/jackw01.github.io
title: macro rail
hide_first_h1: true
plugins:
  - jekyll-seo-tag
custom_buttons:
  - 1:
    url: https://1drv.ms/f/s!AsRZF_y9JrDUoLtMd405sSX-Ant2sQ?e=O6MsAh
    text: Download CAD and STL Files
